// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package matchPoint;

/************************************************************/
/**
 * 
 */
class Campo {
	/**
	 * 
	 */
	public int ID;
	/**
	 * 
	 */
	public TipologiaCampo tipologiaCampo;
	/**
	 * 
	 */
	public int costoOraNotturna;
	/**
	 * 
	 */
	public int costoOraDiurna;
	/**
	 * 
	 */
	public int lunghezza;
	/**
	 * 
	 */
	public int larghezza;
	/**
	 * 
	 */
	public boolean coperto;
	/**
	 * 
	 */
	public Giocatore[] giocatore;

	/**
	 * 
	 * @param inizio 
	 * @param fine 
	 */
	public void libero(EDate inizio, EDate fine) {
	}
}
