// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package matchPoint;

/************************************************************/
/**
 * 
 */
public class Giocatore extends Utente {
	/**
	 * 
	 */
	public Campo[] campo;
}
