// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package individui;

import java.util.Date;

public class Gestore extends Utente {

	public Gestore(String nome, String cognome, Date dataNascita) {
		super(nome, cognome, dataNascita);
	}

	@Override
	public void registrazione() {
		
	}

	@Override
	public void login() {
		
	}
}
