// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package individui;

import java.util.Date;

import components.Campo;

public class Giocatore extends Utente {
	public Giocatore(String nome, String cognome, Date dataNascita) {
		super(nome, cognome, dataNascita);
	}
	public Campo[] campo;

	@Override
	public void registrazione() {
		
	}

	@Override
	public void login() {
		
	}
}
