package individui;

import java.util.Date;

//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

public abstract class Utente {
	public int ID;
	public String nome;
	public String cognome;
	public Date dataNascita;
	public int eta;

	public Utente(String nome, String cognome, Date dataNascita) {
		super();
		this.nome = nome;
		this.cognome = cognome;
		this.dataNascita = dataNascita;
	}

	public Utente() {

	}

	public abstract void registrazione();

	public abstract void login();

}
