// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package components;

class Servizi {
	public Campo[] campo;
	public String nome;
}
