// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package components;

class Servizi {
	public Campo[] campo;
	public String nome;
	public String descrizione;
	public int prezzo;
}
