// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UML;

/************************************************************/
/**
 * 
 */
public class CentroSportivo {
	/**
	 * 
	 */
	public Campo[] campo;
	/**
	 * 
	 */
	public int ID;
	/**
	 * 
	 */
	public String nome;
	/**
	 * 
	 */
	public String[] provincia;
	/**
	 * 
	 */
	public String comune;
}
