// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UML;

/************************************************************/
/**
 * 
 */
public class Gestore extends Utente {
	/**
	 * 
	 */
	public String Certificazione;
	/**
	 * 
	 */
	public String Competenze;
}
