// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package UML;

/************************************************************/
/**
 * 
 */
public abstract class Utente {
	/**
	 * 
	 */
	public int ID;
	/**
	 * 
	 */
	public String nome;
	/**
	 * 
	 */
	public String cognome;
	/**
	 * 
	 */
	public EDate dataNascita;
	/**
	 * 
	 */
	public int eta;

	/**
	 * 
	 */
	public void registrazione() {
	}

	/**
	 * 
	 */
	public void login() {
	}
}
