// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package components;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Date;
import java.util.Objects;

import dataBase.DataBase;
import individui.Giocatore;

public class Campo {
	public int ID;
	public TipologiaCampo tipologiaCampo;
	public int costoOraNotturna;
	public int costoOraDiurna;
	public int lunghezza;
	public int larghezza;
	public boolean coperto;
	private int centroID;
//	public Giocatore[] giocatore;

	@Override
	public String toString() {
		return "Campo [tipologiaCampo=" + tipologiaCampo + ", costoOraNotturna=" + costoOraNotturna
				+ ", costoOraDiurna=" + costoOraDiurna + ", lunghezza=" + lunghezza + ", larghezza=" + larghezza
				+ ", coperto=" + coperto + "]";
	}

	/**
	 * 
	 * @param inizio 
	 * @param fine 
	 */
	public void libero(Date inizio, Date fine) {
	}

	public Campo(TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza, int larghezza,
			boolean coperto) {
		super();
		this.tipologiaCampo = tipologiaCampo;
		this.costoOraNotturna = costoOraNotturna;
		this.costoOraDiurna = costoOraDiurna;
		this.lunghezza = lunghezza;
		this.larghezza = larghezza;
		this.coperto = coperto;
	}
	
	public Campo(int id, TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza, int larghezza,
			boolean coperto) {
		super();
		this.ID=id;
		this.tipologiaCampo = tipologiaCampo;
		this.costoOraNotturna = costoOraNotturna;
		this.costoOraDiurna = costoOraDiurna;
		this.lunghezza = lunghezza;
		this.larghezza = larghezza;
		this.coperto = coperto;
	}
	
	public Campo(int id, TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza, int larghezza,
			boolean coperto, int centroID) {
		super();
		this.ID=id;
		this.tipologiaCampo = tipologiaCampo;
		this.costoOraNotturna = costoOraNotturna;
		this.costoOraDiurna = costoOraDiurna;
		this.lunghezza = lunghezza;
		this.larghezza = larghezza;
		this.coperto = coperto;
		this.centroID = centroID;
	}
	
	@Override
	public boolean equals(Object obj) {
	    if (this == obj) return true;
	    if (obj == null || getClass() != obj.getClass()) return false;
	    Campo campo = (Campo) obj;
	    return costoOraDiurna == campo.costoOraDiurna &&
	           costoOraNotturna == campo.costoOraNotturna &&
	           lunghezza == campo.lunghezza &&
	           larghezza == campo.larghezza &&
	           coperto == campo.coperto &&
	           tipologiaCampo == campo.tipologiaCampo;
	}

	@Override
	public int hashCode() {
	    return Objects.hash(tipologiaCampo, costoOraDiurna, costoOraNotturna, lunghezza, larghezza, coperto);
	}

	
	@Override
	public Campo clone() {
	    return new Campo(this.tipologiaCampo, this.costoOraDiurna, this.costoOraNotturna, this.lunghezza, this.larghezza, this.coperto);
	}

	public static void inserisci(String tipologia, int CostoOraNotturna, int costoOraDiurna, int lunghezza, int larghezza, boolean coperto, int centro) {
		String url = "jdbc:sqlite:src/main/java/dataBase/matchpointDB.db"; //connessione al database
		try  (Connection conn = DriverManager.getConnection(url)){
			DataBase.insert(conn, tipologia, CostoOraNotturna, costoOraDiurna, lunghezza, larghezza, coperto, centro);
		} catch (SQLException e) {
			e.printStackTrace();
		} 
}

	public String getTipologiaCampo() {
		return tipologiaCampo.toString();
	}

	public void setTipologiaCampo(TipologiaCampo tipologiaCampo) {
		this.tipologiaCampo = tipologiaCampo;
	}

	public int getCostoOraNotturna() {
		return costoOraNotturna;
	}

	public void setCostoOraNotturna(int costoOraNotturna) {
		this.costoOraNotturna = costoOraNotturna;
	}
	public int getId() {
		return ID;
	}
	public int getCostoOraDiurna() {
		return costoOraDiurna;
	}

	public void setCostoOraDiurna(int costoOraDiurna) {
		this.costoOraDiurna = costoOraDiurna;
	}

	public int getLunghezza() {
		return lunghezza;
	}

	public void setLunghezza(int lunghezza) {
		this.lunghezza = lunghezza;
	}

	public int getLarghezza() {
		return larghezza;
	}

	public void setLarghezza(int larghezza) {
		this.larghezza = larghezza;
	}

	public boolean isCoperto() {
		return coperto;
	}

	public void setCoperto(boolean coperto) {
		this.coperto = coperto;
	}
	
	public int getCentroId() {
		return centroID;
	}
}
