package components;

import java.util.Objects;

//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

/**
 * Classe che rappresenta un campo da gioco nel sistema.
 */

public class Campo {

    public int ID;
    public TipologiaCampo tipologiaCampo;
    public int costoOraNotturna;
    public int costoOraDiurna;
    public int lunghezza;
    public int larghezza;
    public boolean coperto;
    private int centroID;

    /**
     * Costruttore base per la classe Campo.
     *
     * @param tipologiaCampo  Tipologia del campo.
     * @param costoOraNotturna Costo per ora notturna.
     * @param costoOraDiurna   Costo per ora diurna.
     * @param lunghezza        Lunghezza del campo.
     * @param larghezza        Larghezza del campo.
     * @param coperto          Indica se il campo è coperto.
     */
    public Campo(TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza, int larghezza,
                 boolean coperto) {
        this.tipologiaCampo = tipologiaCampo;
        this.costoOraNotturna = costoOraNotturna;
        this.costoOraDiurna = costoOraDiurna;
        this.lunghezza = lunghezza;
        this.larghezza = larghezza;
        this.coperto = coperto;
    }

    /**
     * Costruttore con ID per la classe Campo.
     *
     * @param id              ID del campo.
     * @param tipologiaCampo  Tipologia del campo.
     * @param costoOraNotturna Costo per ora notturna.
     * @param costoOraDiurna   Costo per ora diurna.
     * @param lunghezza        Lunghezza del campo.
     * @param larghezza        Larghezza del campo.
     * @param coperto          Indica se il campo è coperto.
     */
    public Campo(int id, TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza,
                 int larghezza, boolean coperto) {
        this(tipologiaCampo, costoOraNotturna, costoOraDiurna, lunghezza, larghezza, coperto);
        this.ID = id;
    }

    /**
     * Costruttore completo con centro ID.
     *
     * @param id              ID del campo.
     * @param tipologiaCampo  Tipologia del campo.
     * @param costoOraNotturna Costo per ora notturna.
     * @param costoOraDiurna   Costo per ora diurna.
     * @param lunghezza        Lunghezza del campo.
     * @param larghezza        Larghezza del campo.
     * @param coperto          Indica se il campo è coperto.
     * @param centroID         ID del centro associato.
     */
    public Campo(int id, TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza,
                 int larghezza, boolean coperto, int centroID) {
        this(id, tipologiaCampo, costoOraNotturna, costoOraDiurna, lunghezza, larghezza, coperto);
        this.centroID = centroID;
    }

    @Override
    public String toString() {
        return "Campo [tipologiaCampo=" + tipologiaCampo + ", costoOraNotturna=" + costoOraNotturna
                + ", costoOraDiurna=" + costoOraDiurna + ", lunghezza=" + lunghezza + ", larghezza=" + larghezza
                + ", coperto=" + coperto + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Campo campo = (Campo) obj;
        return costoOraDiurna == campo.costoOraDiurna &&
               costoOraNotturna == campo.costoOraNotturna &&
               lunghezza == campo.lunghezza &&
               larghezza == campo.larghezza &&
               coperto == campo.coperto &&
               tipologiaCampo == campo.tipologiaCampo;
    }

    @Override
    public int hashCode() {
        return Objects.hash(tipologiaCampo, costoOraDiurna, costoOraNotturna, lunghezza, larghezza, coperto);
    }

    @Override
    public Campo clone() {
        return new Campo(this.tipologiaCampo, this.costoOraNotturna, this.costoOraDiurna, this.lunghezza, this.larghezza, this.coperto);
    }

    public String getTipologiaCampo() {
        return tipologiaCampo.toString();
    }

    public void setTipologiaCampo(TipologiaCampo tipologiaCampo) {
        this.tipologiaCampo = tipologiaCampo;
    }

    public int getCostoOraNotturna() {
        return costoOraNotturna;
    }

    public void setCostoOraNotturna(int costoOraNotturna) {
        this.costoOraNotturna = costoOraNotturna;
    }

    public int getId() {
        return ID;
    }

    public int getCostoOraDiurna() {
        return costoOraDiurna;
    }

    public void setCostoOraDiurna(int costoOraDiurna) {
        this.costoOraDiurna = costoOraDiurna;
    }

    public int getLunghezza() {
        return lunghezza;
    }

    public void setLunghezza(int lunghezza) {
        this.lunghezza = lunghezza;
    }

    public int getLarghezza() {
        return larghezza;
    }

    public void setLarghezza(int larghezza) {
        this.larghezza = larghezza;
    }

    public boolean isCoperto() {
        return coperto;
    }

    public void setCoperto(boolean coperto) {
        this.coperto = coperto;
    }

    public int getCentroId() {
        return centroID;
    }
}