// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package components;

import java.util.Date;
import java.util.Objects;

import individui.Giocatore;

public class Campo {
	public int ID;
	public TipologiaCampo tipologiaCampo;
	public int costoOraNotturna;
	public int costoOraDiurna;
	public int lunghezza;
	public int larghezza;
	public boolean coperto;
	public Giocatore[] giocatore;

	@Override
	public String toString() {
		return "Campo [tipologiaCampo=" + tipologiaCampo + ", costoOraNotturna=" + costoOraNotturna
				+ ", costoOraDiurna=" + costoOraDiurna + ", lunghezza=" + lunghezza + ", larghezza=" + larghezza
				+ ", coperto=" + coperto + "]";
	}

	/**
	 * 
	 * @param inizio 
	 * @param fine 
	 */
	public void libero(Date inizio, Date fine) {
	}

	public Campo(TipologiaCampo tipologiaCampo, int costoOraNotturna, int costoOraDiurna, int lunghezza, int larghezza,
			boolean coperto) {
		super();
		this.tipologiaCampo = tipologiaCampo;
		this.costoOraNotturna = costoOraNotturna;
		this.costoOraDiurna = costoOraDiurna;
		this.lunghezza = lunghezza;
		this.larghezza = larghezza;
		this.coperto = coperto;
	}
	
	@Override
	public boolean equals(Object obj) {
	    if (this == obj) return true;
	    if (obj == null || getClass() != obj.getClass()) return false;
	    Campo campo = (Campo) obj;
	    return costoOraDiurna == campo.costoOraDiurna &&
	           costoOraNotturna == campo.costoOraNotturna &&
	           lunghezza == campo.lunghezza &&
	           larghezza == campo.larghezza &&
	           coperto == campo.coperto &&
	           tipologiaCampo == campo.tipologiaCampo;
	}

	@Override
	public int hashCode() {
	    return Objects.hash(tipologiaCampo, costoOraDiurna, costoOraNotturna, lunghezza, larghezza, coperto);
	}

	
	@Override
	public Campo clone() {
	    return new Campo(this.tipologiaCampo, this.costoOraDiurna, this.costoOraNotturna, this.lunghezza, this.larghezza, this.coperto);
	}


}
