// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package components;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import dataBase.DataBase;
import individui.Gestore;

public class CentroSportivo
{
	public Gestore gestore;
	public int ID;
	public String nome;
	public String provincia;	
	public String comune;
	
	public CentroSportivo(Gestore gestore, int iD, String nome, String provincia, String comune) {
		super();
		this.gestore = gestore;
		ID = iD;
		this.nome = nome;
		this.provincia = provincia;
		this.comune = comune;
	}
	
	public static void inserisci(String nome, String provincia, String comune) {
			String url = "jdbc:sqlite:src/main/java/dataBase/matchpointDB.db"; //connessione al database
			try  (Connection conn = DriverManager.getConnection(url)){
				DataBase.insert(conn, nome, provincia, comune, Sessione.getId());
			} catch (SQLException e) {
				e.printStackTrace();
			} 
	}
	
}
