// --------------------------------------------------------
// Code generated by Papyrus Java 
// --------------------------------------------------------

package components;

public enum TipologiaCampo {
	calcioA5,
	calcioA7,
	calcioA9,
	calcioA11,
	basket,
	tennis,
	padel,
	volley,
	golf,
	badminton;
	
}


