package individui;

import java.sql.*;
import java.sql.Date;

import GUI.CustomMessage;
import dataBase.DataBase;

//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

public abstract class Utente {
	public int ID;
	public String nome;
	public String cognome;
	public Date dataNascita;
	public int eta;
	public String username;
	public String password;

	public Utente() {
		super();
	}

	/**
	 *  Metodo per esecuzione del login
	 * @param username
	 * @param password
	 * @return >0 succesful, =0 incorrect password, <0 no username in table
	 * 
	 */
	public static int login(String username, String password) {
		String sql="SELECT Password FROM Gestore WHERE Username ='"+username+"' UNION SELECT Password FROM Giocatore WHERE Username ='"+username+"'";//creazione query
		String url = "jdbc:sqlite:src/main/java/dataBase/matchpointDB.db"; //connessione al database
		String ris="";
		try  (Connection conn = DriverManager.getConnection(url)){
			ris = DataBase.eseguiSelect(conn, sql);//esecuzione select
		} catch (SQLException e) {
			e.printStackTrace();
		} //risultato della query
		System.out.println(ris);
		if(password.equals(ris)) {//confronto con password inserita
			return 1;
		}
		else if(ris.equals("")) {
			System.out.println("Username non trovato!");//se la select non produce risultati
			return -3;
		}
		else {
			System.out.println("Password errata!");
			return 0;
		}
		
	}
	public static String getRuoloUtente(String username, String password) {
	    String ruolo = null;
	    String url = "jdbc:sqlite:src/main/java/dataBase/matchpointDB.db"; // Connessione al database

	    try (Connection conn = DriverManager.getConnection(url)) {
	        // Query per verificare se l'utente è un Gestore
	        String queryGestore = "SELECT username FROM Gestore WHERE username = '" + username + "' AND password = '" + password + "'";
	        String risultatoGestore = DataBase.eseguiSelect(conn, queryGestore);

	        if (risultatoGestore != null && !risultatoGestore.isEmpty()) {
	            ruolo = "Gestore";
	        } else {
	            // Query per verificare se l'utente è un Giocatore
	            String queryGiocatore = "SELECT username FROM Giocatore WHERE username = '" + username + "' AND password = '" + password + "'";
	            String risultatoGiocatore = DataBase.eseguiSelect(conn, queryGiocatore);

	            if (risultatoGiocatore != null && !risultatoGiocatore.isEmpty()) {
	                ruolo = "Giocatore";
	            }
	        }
	    } catch (SQLException e) {
	        e.printStackTrace();
	        CustomMessage.show("Errore durante il recupero del ruolo dell'utente!", "Errore", false);
	    }

	    return ruolo; // Restituisce "Gestore", "Giocatore", oppure null se non trovato
	}



	/*public static int registrazione(String nome, String cognome, Date dataNascita, String email, String username,
			String password, String certificazioni, String competenze) {
		Gestore.registrazione(nome, cognome, dataNascita, email, username, password, certificazioni, competenze);
		return 0;
	}
	
	public static int registrazione(String nome, String cognome, Date dataNascita, String email, String username,
			String password, String nomeSquadra) {
		return 0;
	}
*/
}
